### PR TITLE
Changed PagedMenu for csgo and added manual back option

### PR DESCRIPTION
**Pull request by high-voltage**
As to the issues #52 and #53 I've made changes and tested them, they work well. Maybe you want to use it :)

Working example code:

```

from events import Event

from players.helpers import index_from_userid

from menus import SimpleMenu, SimpleOption, PagedMenu, PagedOption



@Event
def player_jump(game_event):
    userid = game_event.get_int('userid')
    index = index_from_userid(userid)
    some_menu(index)
    
    
def some_menu(index):
    menu = SimpleMenu()
    menu.append(SimpleOption(1, 'some other menu', 1))
    menu.select_callback = some_menu_callback
    menu.send(index)

def some_menu_callback(menu, index, option):
    if option.value == 1:
        some_other_menu(index)

def some_other_menu(index):
    """
     Added a "manual_back_option" parameter, which is defaulted to None.
     When pressing the "Back" button in the first page of the menu,
     this will be passed as option.value in the callback.
    """
   
    menu = PagedMenu(manual_back_option='go_back')
    
    for x in range(1, 30):
        menu.append(PagedOption(x, x))

    menu.select_callback = some_other_menu_callback
    menu.send(index)

def some_other_menu_callback(menu, index, option):
    if option.value == "go_back":
        return some_menu(index)

    print(option.value)

```

### CODE REVIEW

**Comment by high-voltage** [comment]
I guess that counts only for the numbers of the buttons (7,8,9 / 8,9,0), what about the manual_back_option parameter?

**Comment by necavi** [comment]
This can't really be data driven, considering it is based on a client-side binding and only affects one game.

**Comment by satoon101** [comment]
The back option (on the first page) could have a menu assigned to it.  Not sure I would call it manual_back_option, more like parent_menu which would default to None.

The buttons is what I was talking about.  And yes, it can certainly be data driven.

**Comment by high-voltage** [comment]
If we have it parent_menu, it should most likely automatically call a menu. But wouldn't this require to have all our menus (or atleast the needed ones) in the global scope or saved in a dict? I think it's the best way to have it like I intended, maybe just not the name "manual_back_option" but I couldn't come up with something that sounds better.

**Comment by satoon101** [comment]
They wouldn't all have to be in the global scope.  When declaring the parent_menu for a child menu, it would just require access to the parent menu's instance.

**Comment by MarkusMeskanen** [comment]
This actually is a "problem" in the current implementation too; say I want to have 5 menus, one "Main Menu" and 4 sub menus. If I have them all in the same file, my main menu must be the last one since it "needs to" (should?) have the other 4 menus accessible in it's constructor. It would be better in the first place if the menu content would somehow be defined in a function instead of a global menu instance. Just my opinion. :)

**Comment by satoon101** [comment]
All menus inherit from list.  This allows you to append options/text to the menu in order.

**Comment by MarkusMeskanen** [comment]
I understand, but I can't see why they couldn't just contain a list and have similar methods like `add` etc.

I think every menu should be subclassed from some kind of base menu, and the build callback and select callback would be methods that override the base menu's methods. This way your menus could basically do anything without having to worry about whether the other menus in global scope are defined before them. At least that's how I'd do it, any reason not to do it this way? :)

**Comment by satoon101** [comment]
Why would it contain a list when it "is" a list?  And you use the "append" method to add items.  Unless I am missing something, I think you already do that with build and select callbacks.  The only thing with them being in the global scope is that they cancel/close automatically when the script unloads.

**Comment by high-voltage** [comment]
Back to the "back" option, let's take my example script above as an example. 
If we would have the "parent_menu" parameter, which requires a menu instance, I would have to make the menu in "def some_menu(index)" in the global scope or save it somewhere else. I personally don't like to do that, and it would complicate everything even more if the parented menu displays player specific information, which could refresh while browsing through the menus.

**Comment by MarkusMeskanen** [comment]
Satoon, the idea would be that you don't need to have the sub menus defined before the main menu (in global scope f.e.).

It really isn't that big of an issue, but here's what I mean: https://gist.github.com/MarkusMeskanen/5301961ee6a384aef768

But probably not worth the time or anything :)

**Comment by satoon101** [comment]
The items are what make up the menu.  It makes perfect sense to me.  Check your link above again, as Ayuto and I have provided further examples.

**Comment by satoon101** [comment]
@high-voltage, if we added it as a parameter, we would also store it as an attribute.  That way you can not pass it on instantiation and set the value later.

**Comment by Ayuto** [comment]
Due to PR #111 I will close this.

**Pull request closed without merging**
