### PR TITLE
Added **kwargs support for menu translations

### PR DESCRIPTION
**Pull request by MarkusMeskanen**
All menus now support keyword arguments when translating them. This
includes _MenuData classes (texts and options), descriptions, and
titles.

### CODE REVIEW

**Comment by Ayuto** [comment]
There are a couple of issues with this implementation. At first the name "kwargs" is very ambiguous. A better name would be "tokens". The description would also need to be changed. However, this isn't a real problem, but one problem I see here is that you can't use "**kwargs", because every method has keywords. That would result in unusable token names like "value", "selectable", etc. Of course, this could be fixed by just using a new keyword "tokens=None".

However, I don't think this is the right approach, because these tokens are just statically passed to the translator function. If you want to update the tokens you would need to do something like this:
```
menu.description_tokens.update(...)
```
But that's just unecessary, because you can just do this:
```
menu.description.tokens.update(...)
```
So, the real problem we have here, is that you can't get a TranslationStrings object with an initialized tokens dictionary. We could simply work around that by adding this method to the LangStrings class:
```
    def get_translation_strings(self, key, **tokens):
        strings = self[key]
        strings.update(tokens)
        return strings
```
To show both methods in contrast:
```
# Your method
PagedMenu(description=my_strings['test'], description_tokens=dict(token1='abc', token2='bla'))

# Better, imo
PagedMenu(description=my_strings.get_translation_strings('test', token1='abc', token2='bla'))
```

**Comment by MarkusMeskanen** [comment]
Oh, right :) Well I wasn't actually expecting this exact code to get accepted, I just gave my shot and was hoping people would come up with something. Apparently your solution was nothing similar, but much better.

However, it would be cool to get some sort of translation keywords for menus. I currently use the kwargs=None and self.kwargs = kwargs or {} solution, waiting for something better to show up.

**Comment by Ayuto** [comment]
For now you can just move this method somewhere in your code. You can then do something like this:
```
def get_translation_strings(self, key, **tokens):
    strings = self[key]
    strings.update(tokens)
    return strings
    
menu = PagedMenu(description=get_translation_strings(my_strings, 'test', token1='abc'))
```
But I would still like to hear a third or fourth opinion on this.

**Comment by MarkusMeskanen** [comment]
Yeah I figured, I already did that :)

**Comment by MarkusMeskanen** [comment]
Yeah I figured, I already did that :) After re-reading your first comment a few times, that is.

**Comment by Ayuto** [comment]
Since there was no more feedback, I added the get_strings() method. https://github.com/Source-Python-Dev-Team/Source.Python/commit/9507fd60db2309d058849cff7e3133b971d791d9

**Pull request closed without merging**
