### PR TITLE
Fixes weapon restriction

### PR DESCRIPTION
**Pull request by ThaPwned**
More information:
http://forums.sourcepython.com/viewtopic.php?f=20&p=9791#p9791

### CODE REVIEW

**Comment by satoon101** [comment]
This will have the same issue that already exists, as it is still clearing the _TeamRestrictions dictionaries.  The ```for loop``` is fine by itself as a fix, or you can instead override _TeamRestrictions.clear() to do the same ```for loop``` internally.  I think option 2 would be the better choice in case other developers want to override WeaponRestrictionHandler's clear method.

**Comment by ThaPwned** [comment]
> This will have the same issue that already exists

It won't. Have been running my test server with the code for quite a while now without any exceptions but I'll update the code with your suggestion.

**Comment by satoon101** [comment]
You must not have tested with a map change, then.

In [OnLevelInit](https://github.com/Source-Python-Dev-Team/Source.Python/blob/79593cbf43dfd444d9484c5daaa355e5d82ef8ea/addons/source-python/packages/source-python/weapons/restrictions.py#L397-#L400), we [clear the all of the registered handlers](https://github.com/Source-Python-Dev-Team/Source.Python/blob/79593cbf43dfd444d9484c5daaa355e5d82ef8ea/addons/source-python/packages/source-python/weapons/restrictions.py#L158-#L161).  So, that in turn [clears the team_restrictions of all items](https://github.com/Source-Python-Dev-Team/Source.Python/blob/79593cbf43dfd444d9484c5daaa355e5d82ef8ea/addons/source-python/packages/source-python/weapons/restrictions.py#L204-#L207) for each handler.  Since there are no more items in the team_restrictions, `__getitem__` [will error](https://github.com/Source-Python-Dev-Team/Source.Python/blob/79593cbf43dfd444d9484c5daaa355e5d82ef8ea/addons/source-python/packages/source-python/weapons/restrictions.py#L179-#L191) whether you pass a team number or an alias.

Thank you for the update!

**Comment by ThaPwned** [comment]
I could've sworn it did... I take my statement back.
> Thank you for the update!

You're welcome.

**Pull request merged**
