### PR TITLE
Menus: Add register_close_callback decorator

### PR DESCRIPTION
**Pull request by backraw**
Simple usage example:
```python
from menus import PagedMenu
from menus import PagedOption
from players.entity import Player

main_menu = PagedMenu(
    [
        PagedOption('Say Hi', 0),
        PagedOption('Say something else', 1)
    ], title='Main Menu'
)


@main_menu.register_select_callback
def main_menu_select(menu, index, option):
    print(option.text)

@main_menu.register_close_callback
def main_menu_closed(menu, index):
    player = Player(index)
    print(f'Player {player.name} closed {menu.title}')
```

If you have any change requests, post them here :)

### CODE REVIEW

**Comment by backraw** [comment]
Ignore the second commit reference - didn't know it would show up here.

**Comment by satoon101** [comment]
To revise my review, the overall issue is that you explicitly check against `0` in the base `_select`, which would be incorrect for CS:GO and BM:S.

**Comment by satoon101** [comment]
In case you didn't see my edit, I think the best thing to do is move the 2 lines you added to the base `_select` into their own method.  That method should only check to see if the callback is None, and if not, call it.  Then, instead of calling `super()._select()`, call this new method, as there is nothing else in the base `_select` that should be ran anyway.

**Comment by backraw** [comment]
Got it. I'm done - downloading a HL2MP server atm.

**Comment by backraw** [comment]
Updated to d6c8daa. Tested with CS:S, CS:GO and HL2MP.
The following script works as expected:
```python

# =============================================================================
# >> IMPORTS
# =============================================================================
from events import Event

from menus import SimpleMenu
from menus import SimpleOption
from menus import PagedMenu
from menus import PagedOption

from messages import SayText2

from players.helpers import index_from_userid


# =============================================================================
# >> SIMPLE MENU
# =============================================================================
simple_menu = SimpleMenu(
    [
        'Menu Title',
        SimpleOption(1, 'Choice 1'),
        SimpleOption(2, 'Choice 2'),
        0
    ]
)


@simple_menu.register_select_callback
def simple_menu_select(menu, index, option):
    SayText2(f'Simple Menu: Selected {option.text} ({option.choice_index})').send(index)
    simple_menu.send(index)


@simple_menu.register_close_callback
def simple_menu_close(menu, index):
    SayText2(f'Simple Menu: Closed').send(index)


# =============================================================================
# >> PAGED MENU
# =============================================================================
paged_menu = PagedMenu(
    [
        PagedOption('Choice: None', None),
        PagedOption('Choice: Text', 'Some text'),
        PagedOption('Choice: Int', 802)
    ], title='Paged Menu'
)


@paged_menu.register_select_callback
def paged_menu_select(menu, index, option):
    SayText2(f'{menu.title}: Selected {option.text} ({option.value})').send(index)
    paged_menu.send(index)


@paged_menu.register_close_callback
def paged_menu_close(menu, index):
    SayText2(f'{menu.title}: Closed').send(index)


@Event('player_say')
def on_player_say(game_event):
    index = index_from_userid(game_event['userid'])
    text = game_event['text']

    if text == 'simple':
        simple_menu.send(index)
    elif text == 'paged':
        paged_menu.send(index)
```

**Comment by satoon101** [comment]
Looks good to me.  I'll wait for other opinions before merging.  Thank you!

**Comment by backraw** [comment]
Glad I could help :)

**Comment by invincibleqc** [comment]
Looks good to me too. Noticed some copy/pasted documentation that doesn't makes any sense tho.
>2. The index of the player who will receive this menu.

The player won't receive the menu if he just closed it. 😆

**Comment by backraw** [comment]
Updated to 1921b38. I would like to mention that in the previous commits I forgot to add ```close_callback``` to ```ListESCMenu```'s constructor. Fixed with the latest commit.

**Comment by Ayuto** [comment]
Looks good, thank you!

**Pull request merged**
