### PR TITLE
Changed the slot values to be in line with Valve's weapon slots.

### PR DESCRIPTION
**Pull request by vinci6k**
Seems the values were offset by 1.

### CODE REVIEW

**Comment by Ayuto** [comment]
The values are still correct. Why do you think they have changed?

**Comment by vinci6k** [comment]
When I run this (with the current WeaponSlot.ini):
```python
# ../weapon_slot/weapon_slot.py

# Source.Python
from players.dictionary import PlayerDictionary
from weapons.constants import WeaponSlot
from weapons.manager import weapon_manager
from commands.say import SayCommand


player_instances = PlayerDictionary()


@SayCommand('test')
def test_cmd(command, index, team_only=False):
    player = player_instances[index]
    weapon = player.active_weapon

    print(weapon.classname)
    print(WeaponSlot(weapon_manager.get(weapon.classname).slot))
```
I'm getting this as the output:
```
Tesla: test
weapon_m4a1
WeaponSlot.SECONDARY

Tesla: test
weapon_glock
WeaponSlot.KNIFE

Tesla: test
weapon_knife
WeaponSlot.GRENADE
```

**Comment by Ayuto** [comment]
Ah, I see. However, while updating ``WeaponSlot.ini`` would fix the issue, we won't be in line anymore with Valve's weapon slots. To fix the issue and still stay in line with Valve, we would need to update this file:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/data/source-python/weapons/cstrike.ini

This snippet retrieves Valve's weapon slots:
```python
from players.entity import Player
from weapons.entity import Weapon
from memory import DataType, make_object, Convention
from core import PLATFORM

player = Player(1)

Weapon_GetSlot = player.pointer.make_virtual_function(
    268 if PLATFORM == 'windows' else 269,
    Convention.THISCALL,
    [DataType.POINTER, DataType.INT],
    DataType.POINTER)
    
for x in range(5):
    ptr = Weapon_GetSlot(player, x)
    if ptr:
        weapon = make_object(Weapon, ptr)
        print(x, weapon.classname)
```

**Comment by vinci6k** [comment]
I guess I was used to the keybinds for weapon switching in games, which is why I thought WeaponSlot.ini was incorrect.

I've changed WeaponSlot.ini back to what it was, and I've updated the slot values for CSS, CSGO, and HL2DM.

**Comment by Ayuto** [comment]
Thanks!

**Pull request merged**
